import React from 'react'
import { Download, Printer, FolderPlus } from 'lucide-react'
import { RiskBadge } from './Feedback'
import { fmtDate, fmtBytes } from '../utils/helpers'

const AUTH_BADGE = {
  'LIKELY AUTHENTIC': 'authentic', 'REVIEW RECOMMENDED': 'review',
  'SUSPICIOUS': 'suspicious', 'LIKELY MANIPULATED': 'manipulated',
}

export default function ReportPreview({ evidence, onNew }) {
  const r = evidence?.result
  if (!evidence || !r) return null

  const signalRows = [
    ['Visual', r.visualScore], ['Audio', r.audioScore], ['Temporal', r.temporalScore],
    ['Compression', r.compressionScore], ['Cross-Modal', r.crossModalScore],
  ]

  const download = () => {
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>DeepTrace Report ${evidence.caseId}</title>
<style>body{font-family:system-ui;color:#111;max-width:820px;margin:40px auto;padding:0 20px}h1{letter-spacing:.15em}h2{font-size:.8rem;letter-spacing:.18em;color:#1d4ed8;border-left:3px solid #1d4ed8;padding-left:10px;margin-top:28px}table{border-collapse:collapse;width:100%;font-size:.9rem}td,th{border:1px solid #ccc;padding:8px 10px;text-align:left}.warn{background:#fff8e6;border:1px dashed #d9a514;padding:12px;font-size:.85rem;margin-top:24px}</style></head><body>
<h1>DEEPTRACE</h1><p><strong>DIGITAL FORENSICS REPORT</strong> — DEMO / SIMULATED ANALYSIS</p>
<h2>CASE INFORMATION</h2><table>
<tr><th>Case ID</th><td>${evidence.caseId}</td></tr>
<tr><th>Evidence ID</th><td>${evidence.id}</td></tr>
<tr><th>Filename</th><td>${evidence.filename}</td></tr>
<tr><th>Media Type</th><td>${evidence.type}</td></tr>
<tr><th>Analysis Date</th><td>${fmtDate(evidence.date)}</td></tr></table>
<h2>FINAL ASSESSMENT</h2><table>
<tr><th>Authenticity Score</th><td>${r.authenticityScore}%</td></tr>
<tr><th>Classification</th><td>${r.classification}</td></tr>
<tr><th>Confidence</th><td>${r.confidence}%</td></tr>
<tr><th>Risk Level</th><td>${r.risk}</td></tr></table>
<h2>MULTI-SIGNAL ANALYSIS</h2><table><tr><th>Signal</th><th>Score</th></tr>
${signalRows.map(([k, v]) => `<tr><td>${k}</td><td>${v == null ? 'N/A' : v + '%'}</td></tr>`).join('')}</table>
<h2>KEY FINDINGS</h2><table><tr><th>Finding</th><th>Status</th><th>Detail</th></tr>
${r.findings.map((f) => `<tr><td>${f.title}</td><td>${f.status}</td><td>${f.text}</td></tr>`).join('')}</table>
<h2>GENERALIZATION / ROBUSTNESS</h2>
<p>Signal stability after simulated compression &amp; re-encoding: ${r.compressionTest.stability}% (overall ${r.compressionTest.before.overall}% → ${r.compressionTest.after.overall}%).</p>
<div class="warn"><strong>LIMITATIONS:</strong> This report is generated by a hackathon prototype (DEMO / SIMULATED ANALYSIS). Results should not be treated as conclusive forensic evidence.</div>
</body></html>`
    const blob = new Blob([html], { type: 'text/html' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `DeepTrace_Report_${evidence.caseId}_${evidence.id}.html`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div>
      <div className="flex-between no-print" style={{ marginBottom: 18 }}>
        <span className="demo-ribbon"><span className="dot amber" /> DEMO REPORT — SIMULATED ANALYSIS</span>
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
          <button className="btn" onClick={download}><Download size={16} /> Download Report</button>
          <button className="btn" onClick={() => window.print()}><Printer size={16} /> Print Report</button>
          {onNew && <button className="btn btn-primary" onClick={onNew}><FolderPlus size={16} /> New Investigation</button>}
        </div>
      </div>

      <article className="report-sheet" aria-label="Digital forensics report">
        <header className="report-head">
          <div className="report-brand">
            <strong>DEEPTRACE</strong>
            <span>Digital Forensics Report</span>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div className="mono" style={{ color: 'var(--cyan)' }}>{evidence.caseId}</div>
            <div className="mono" style={{ color: 'var(--text-3)', fontSize: '0.7rem' }}>{fmtDate(evidence.date)}</div>
          </div>
        </header>

        <section className="report-section">
          <h3>Case Information</h3>
          <div className="report-kv">
            <div className="kv"><div className="k">Case ID</div><div className="v">{evidence.caseId}</div></div>
            <div className="kv"><div className="k">Evidence ID</div><div className="v">{evidence.id}</div></div>
            <div className="kv"><div className="k">Filename</div><div className="v">{evidence.filename}</div></div>
            <div className="kv"><div className="k">Media Type</div><div className="v">{evidence.type}</div></div>
            <div className="kv"><div className="k">File Size</div><div className="v">{fmtBytes(evidence.size)}</div></div>
            <div className="kv"><div className="k">Analysis Date</div><div className="v">{fmtDate(evidence.date)}</div></div>
          </div>
        </section>

        <section className="report-section">
          <h3>Final Assessment</h3>
          <div className="report-kv">
            <div className="kv"><div className="k">Authenticity Score</div><div className="v" style={{ fontSize: '1.4rem' }}>{r.authenticityScore}%</div></div>
            <div className="kv"><div className="k">Classification</div><div className="v"><span className={`badge ${AUTH_BADGE[r.classification]}`}>{r.classification}</span></div></div>
            <div className="kv"><div className="k">Confidence</div><div className="v">{r.confidence}%</div></div>
            <div className="kv"><div className="k">Risk Level</div><div className="v"><RiskBadge level={r.risk} /></div></div>
          </div>
          <p style={{ color: 'var(--text-2)', fontSize: '0.82rem', marginTop: 12 }}>
            This classification is probabilistic and must not be interpreted as absolute proof of authenticity or manipulation.
          </p>
        </section>

        <section className="report-section">
          <h3>Multi-Signal Analysis</h3>
          <div className="report-kv">
            {signalRows.map(([k, v]) => (
              <div className="kv" key={k}><div className="k">{k} Evidence</div>
                <div className="v">{v == null ? 'N/A' : `${v}%`}</div></div>
            ))}
          </div>
        </section>

        <section className="report-section">
          <h3>Key Findings</h3>
          <div className="table-wrap">
            <table className="data">
              <thead><tr><th>Finding</th><th>Status</th><th>Detail</th></tr></thead>
              <tbody>
                {r.findings.slice(0, 6).map((f) => (
                  <tr key={f.key} style={{ cursor: 'default', whiteSpace: 'normal' }}>
                    <td style={{ whiteSpace: 'nowrap' }}>{f.title}</td>
                    <td><span className={`badge ${f.level === 'normal' ? 'normal' : f.level === 'concern' ? 'concern' : 'suspicious'}`}>{f.status}</span></td>
                    <td style={{ whiteSpace: 'normal', color: 'var(--text-2)' }}>{f.text}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="report-section">
          <h3>Evidence Locations</h3>
          <div className="report-kv">
            {r.suspiciousRegions.length > 0 && (
              <div className="kv"><div className="k">Flagged Regions</div>
                <div className="v">{r.suspiciousRegions.map((x) => x.id).join(', ')}</div></div>
            )}
            {r.suspiciousFrames.length > 0 && (
              <div className="kv"><div className="k">Suspicious Frames</div>
                <div className="v">{r.suspiciousFrames.map((f) => `#${f.frame} @ ${f.time}`).join(' · ')}</div></div>
            )}
            {r.audioSegments.length > 0 && (
              <div className="kv"><div className="k">Audio Segments</div>
                <div className="v">{r.audioSegments.map((s) => `${s.startLabel}–${s.endLabel}`).join(' · ')}</div></div>
            )}
            {r.lipSyncScore != null && (
              <div className="kv"><div className="k">Lip-Sync Consistency</div><div className="v">{r.lipSyncScore}%</div></div>
            )}
          </div>
        </section>

        <section className="report-section">
          <h3>Generalization / Robustness</h3>
          <div className="report-kv">
            <div className="kv"><div className="k">Signal Stability</div><div className="v">{r.compressionTest.stability}%</div></div>
            <div className="kv"><div className="k">Overall Before</div><div className="v">{r.compressionTest.before.overall}%</div></div>
            <div className="kv"><div className="k">Overall After Re-encoding</div><div className="v">{r.compressionTest.after.overall}%</div></div>
          </div>
        </section>

        <div className="limitations">
          <strong>LIMITATIONS:</strong> This report is generated by a hackathon prototype
          (DEMO / SIMULATED ANALYSIS). Results should not be treated as conclusive forensic
          evidence. Scores are produced by a deterministic demonstration heuristic, not a
          scientifically validated AI model.
        </div>
      </article>
    </div>
  )
}
